// Currency options for the currency picker (value = ISO code).
const Currencies = [
  {
    label: "🇦🇪 United Arab Emirates Dirham (AED)",
    value: "AED",
    symbol: "د.إ",
  },
  { label: "🇦🇫 Afghan Afghani (AFN)", value: "AFN", symbol: "؋" },
  { label: "🇦🇱 Albanian Lek (ALL)", value: "ALL", symbol: "L" },
  { label: "🇦🇲 Armenian Dram (AMD)", value: "AMD", symbol: "֏" },
  {
    label: "🇨🇼 Netherlands Antillean Guilder (ANG)",
    value: "ANG",
    symbol: "ƒ",
  },
  { label: "🇦🇴 Angolan Kwanza (AOA)", value: "AOA", symbol: "Kz" },
  { label: "🇦🇷 Argentine Peso (ARS)", value: "ARS", symbol: "$" },
  { label: "🇦🇺 Australian Dollar (AUD)", value: "AUD", symbol: "$" },
  { label: "🇦🇼 Aruban Florin (AWG)", value: "AWG", symbol: "ƒ" },
  { label: "🇦🇿 Azerbaijani Manat (AZN)", value: "AZN", symbol: "₼" },
  {
    label: "🇧🇦 Bosnia-Herzegovina Convertible Mark (BAM)",
    value: "BAM",
    symbol: "KM",
  },
  { label: "🇧🇧 Barbadian Dollar (BBD)", value: "BBD", symbol: "$" },
  { label: "🇧🇩 Bangladeshi Taka (BDT)", value: "BDT", symbol: "৳" },
  { label: "🇧🇬 Bulgarian Lev (BGN)", value: "BGN", symbol: "лв" },
  { label: "🇧🇭 Bahraini Dinar (BHD)", value: "BHD", symbol: ".د.ب" },
  { label: "🇧🇮 Burundian Franc (BIF)", value: "BIF", symbol: "FBu" },
  { label: "🇧🇲 Bermudan Dollar (BMD)", value: "BMD", symbol: "$" },
  { label: "🇧🇳 Brunei Dollar (BND)", value: "BND", symbol: "$" },
  { label: "🇧🇴 Bolivian Boliviano (BOB)", value: "BOB", symbol: "Bs." },
  { label: "🇧🇷 Brazilian Real (BRL)", value: "BRL", symbol: "R$" },
  { label: "🇧🇸 Bahamian Dollar (BSD)", value: "BSD", symbol: "$" },
  { label: "₿ Bitcoin (BTC)", value: "BTC", symbol: "₿" },
  { label: "🇧🇹 Bhutanese Ngultrum (BTN)", value: "BTN", symbol: "Nu." },
  { label: "🇧🇼 Botswanan Pula (BWP)", value: "BWP", symbol: "P" },
  { label: "🇧🇾 New Belarusian Ruble (BYN)", value: "BYN", symbol: "Br" },
  { label: "🇧🇾 Belarusian Ruble (BYR)", value: "BYR", symbol: "Br" },
  { label: "🇧🇿 Belize Dollar (BZD)", value: "BZD", symbol: "$" },
  { label: "🇨🇦 Canadian Dollar (CAD)", value: "CAD", symbol: "$" },
  { label: "🇨🇩 Congolese Franc (CDF)", value: "CDF", symbol: "FC" },
  { label: "🇨🇭 Swiss Franc (CHF)", value: "CHF", symbol: "CHF" },
  {
    label: "🇨🇱 Chilean Unit Of Account (Uf) (CLF)",
    value: "CLF",
    symbol: "UF",
  },
  { label: "🇨🇱 Chilean Peso (CLP)", value: "CLP", symbol: "$" },
  { label: "🇨🇳 Chinese Yuan (CNY)", value: "CNY", symbol: "¥" },
  { label: "🇨🇴 Colombian Peso (COP)", value: "COP", symbol: "$" },
  { label: "🇨🇷 Costa Rican Colón (CRC)", value: "CRC", symbol: "₡" },
  { label: "🇨🇺 Cuban Convertible Peso (CUC)", value: "CUC", symbol: "$" },
  { label: "🇨🇺 Cuban Peso (CUP)", value: "CUP", symbol: "$" },
  { label: "🇨🇻 Cape Verdean Escudo (CVE)", value: "CVE", symbol: "$" },
  { label: "🇨🇿 Czech Republic Koruna (CZK)", value: "CZK", symbol: "Kč" },
  { label: "🇩🇯 Djiboutian Franc (DJF)", value: "DJF", symbol: "Fdj" },
  { label: "🇩🇰 Danish Krone (DKK)", value: "DKK", symbol: "kr" },
  { label: "🇩🇴 Dominican Peso (DOP)", value: "DOP", symbol: "RD$" },
  { label: "🇩🇿 Algerian Dinar (DZD)", value: "DZD", symbol: "دج" },
  { label: "🇪🇬 Egyptian Pound (EGP)", value: "EGP", symbol: "£" },
  { label: "🇪🇷 Eritrean Nakfa (ERN)", value: "ERN", symbol: "Nfk" },
  { label: "🇪🇹 Ethiopian Birr (ETB)", value: "ETB", symbol: "Br" },
  { label: "🇪🇺 Euro (EUR)", value: "EUR", symbol: "€" },
  { label: "🇫🇯 Fijian Dollar (FJD)", value: "FJD", symbol: "$" },
  { label: "🇫🇰 Falkland Islands Pound (FKP)", value: "FKP", symbol: "£" },
  { label: "🇬🇧 British Pound Sterling (GBP)", value: "GBP", symbol: "£" },
  { label: "🇬🇪 Georgian Lari (GEL)", value: "GEL", symbol: "₾" },
  { label: "🇬🇬 Guernsey Pound (GGP)", value: "GGP", symbol: "£" },
  { label: "🇬🇭 Ghanaian Cedi (GHS)", value: "GHS", symbol: "GH₵" },
  { label: "🇬🇮 Gibraltar Pound (GIP)", value: "GIP", symbol: "£" },
  { label: "🇬🇲 Gambian Dalasi (GMD)", value: "GMD", symbol: "D" },
  { label: "🇬🇳 Guinean Franc (GNF)", value: "GNF", symbol: "FG" },
  { label: "🇬🇹 Guatemalan Quetzal (GTQ)", value: "GTQ", symbol: "Q" },
  { label: "🇬🇾 Guyanaese Dollar (GYD)", value: "GYD", symbol: "$" },
  { label: "🇭🇰 Hong Kong Dollar (HKD)", value: "HKD", symbol: "$" },
  { label: "🇭🇳 Honduran Lempira (HNL)", value: "HNL", symbol: "L" },
  { label: "🇭🇷 Croatian Kuna (HRK)", value: "HRK", symbol: "kn" },
  { label: "🇭🇹 Haitian Gourde (HTG)", value: "HTG", symbol: "G" },
  { label: "🇭🇺 Hungarian Forint (HUF)", value: "HUF", symbol: "Ft" },
  { label: "🇮🇩 Indonesian Rupiah (IDR)", value: "IDR", symbol: "Rp" },
  { label: "🇮🇱 Israeli New Sheqel (ILS)", value: "ILS", symbol: "₪" },
  { label: "🇮🇲 Manx Pound (IMP)", value: "IMP", symbol: "£" },
  { label: "🇮🇳 Indian Rupee (INR)", value: "INR", symbol: "₹" },
  { label: "🇮🇶 Iraqi Dinar (IQD)", value: "IQD", symbol: "ع.د" },
  { label: "🇮🇷 Iranian Rial (IRR)", value: "IRR", symbol: "﷼" },
  { label: "🇮🇸 Icelandic Króna (ISK)", value: "ISK", symbol: "kr" },
  { label: "🇯🇪 Jersey Pound (JEP)", value: "JEP", symbol: "£" },
  { label: "🇯🇲 Jamaican Dollar (JMD)", value: "JMD", symbol: "J$" },
  { label: "🇯🇴 Jordanian Dinar (JOD)", value: "JOD", symbol: "ا.د" },
  { label: "🇯🇵 Japanese Yen (JPY)", value: "JPY", symbol: "¥" },
  { label: "🇰🇪 Kenyan Shilling (KES)", value: "KES", symbol: "Sh" },
  { label: "🇰🇬 Kyrgystani Som (KGS)", value: "KGS", symbol: "лв" },
  { label: "🇰🇭 Cambodian Riel (KHR)", value: "KHR", symbol: "៛" },
  { label: "🇰🇲 Comorian Franc (KMF)", value: "KMF", symbol: "CF" },
  { label: "🇰🇵 North Korean Won (KPW)", value: "KPW", symbol: "₩" },
  { label: "🇰🇷 South Korean Won (KRW)", value: "KRW", symbol: "₩" },
  { label: "🇰🇼 Kuwaiti Dinar (KWD)", value: "KWD", symbol: "د.ك" },
  { label: "🇰🇾 Cayman Islands Dollar (KYD)", value: "KYD", symbol: "$" },
  { label: "🇰🇿 Kazakhstani Tenge (KZT)", value: "KZT", symbol: "лв" },
  { label: "🇱🇦 Laotian Kip (LAK)", value: "LAK", symbol: "₭" },
  { label: "🇱🇧 Lebanese Pound (LBP)", value: "LBP", symbol: "£" },
  { label: "🇱🇰 Sri Lankan Rupee (LKR)", value: "LKR", symbol: "₨" },
  { label: "🇱🇷 Liberian Dollar (LRD)", value: "LRD", symbol: "$" },
  { label: "🇱🇸 Lesotho Loti (LSL)", value: "LSL", symbol: "L" },
  { label: "🇱🇹 Lithuanian Litas (LTL)", value: "LTL", symbol: "Lt" },
  { label: "🇱🇻 Latvian Lats (LVL)", value: "LVL", symbol: "Ls" },
  { label: "🇱🇾 Libyan Dinar (LYD)", value: "LYD", symbol: "د.ل" },
  { label: "🇲🇦 Moroccan Dirham (MAD)", value: "MAD", symbol: "د.م." },
  { label: "🇲🇩 Moldovan Leu (MDL)", value: "MDL", symbol: "L" },
  { label: "🇲🇬 Malagasy Ariary (MGA)", value: "MGA", symbol: "Ar" },
  { label: "🇲🇰 Macedonian Denar (MKD)", value: "MKD", symbol: "ден" },
  { label: "🇲🇲 Myanma Kyat (MMK)", value: "MMK", symbol: "K" },
  { label: "🇲🇳 Mongolian Tugrik (MNT)", value: "MNT", symbol: "₮" },
  { label: "🇲🇴 Macanese Pataca (MOP)", value: "MOP", symbol: "MOP$" },
  { label: "🇲🇷 Mauritanian Ouguiya (MRO)", value: "MRO", symbol: "UM" },
  { label: "🇲🇺 Mauritian Rupee (MUR)", value: "MUR", symbol: "₨" },
  { label: "🇲🇻 Maldivian Rufiyaa (MVR)", value: "MVR", symbol: "Rf" },
  { label: "🇲🇼 Malawian Kwacha (MWK)", value: "MWK", symbol: "MK" },
  { label: "🇲🇽 Mexican Peso (MXN)", value: "MXN", symbol: "$" },
  { label: "🇲🇾 Malaysian Ringgit (MYR)", value: "MYR", symbol: "RM" },
  { label: "🇲🇿 Mozambican Metical (MZN)", value: "MZN", symbol: "MT" },
  { label: "🇳🇦 Namibian Dollar (NAD)", value: "NAD", symbol: "$" },
  { label: "🇳🇬 Nigerian Naira (NGN)", value: "NGN", symbol: "₦" },
  { label: "🇳🇮 Nicaraguan Córdoba (NIO)", value: "NIO", symbol: "C$" },
  { label: "🇳🇴 Norwegian Krone (NOK)", value: "NOK", symbol: "kr" },
  { label: "🇳🇵 Nepalese Rupee (NPR)", value: "NPR", symbol: "₨" },
  { label: "🇳🇿 New Zealand Dollar (NZD)", value: "NZD", symbol: "$" },
  { label: "🇴🇲 Omani Rial (OMR)", value: "OMR", symbol: "﷼" },
  { label: "🇵🇦 Panamanian Balboa (PAB)", value: "PAB", symbol: "B/." },
  { label: "🇵🇪 Peruvian Nuevo Sol (PEN)", value: "PEN", symbol: "S/." },
  { label: "🇵🇬 Papua New Guinean Kina (PGK)", value: "PGK", symbol: "K" },
  { label: "🇵🇭 Philippine Peso (PHP)", value: "PHP", symbol: "₱" },
  { label: "🇵🇰 Pakistani Rupee (PKR)", value: "PKR", symbol: "₨" },
  { label: "🇵🇱 Polish Zloty (PLN)", value: "PLN", symbol: "zł" },
  { label: "🇵🇾 Paraguayan Guarani (PYG)", value: "PYG", symbol: "Gs" },
  { label: "🇶🇦 Qatari Rial (QAR)", value: "QAR", symbol: "﷼" },
  { label: "🇷🇴 Romanian Leu (RON)", value: "RON", symbol: "lei" },
  { label: "🇷🇸 Serbian Dinar (RSD)", value: "RSD", symbol: "Дин." },
  { label: "🇷🇺 Russian Ruble (RUB)", value: "RUB", symbol: "₽" },
  { label: "🇷🇼 Rwandan Franc (RWF)", value: "RWF", symbol: "FRw" },
  { label: "🇸🇦 Saudi Riyal (SAR)", value: "SAR", symbol: "﷼" },
  { label: "🇸🇧 Solomon Islands Dollar (SBD)", value: "SBD", symbol: "$" },
  { label: "🇸🇨 Seychellois Rupee (SCR)", value: "SCR", symbol: "₨" },
  { label: "🇸🇩 Sudanese Pound (SDG)", value: "SDG", symbol: "ج.س." },
  { label: "🇸🇪 Swedish Krona (SEK)", value: "SEK", symbol: "kr" },
  { label: "🇸🇬 Singapore Dollar (SGD)", value: "SGD", symbol: "$" },
  { label: "🇸🇭 Saint Helena Pound (SHP)", value: "SHP", symbol: "£" },
  { label: "🇸🇱 Sierra Leonean Leone (SLL)", value: "SLL", symbol: "Le" },
  { label: "🇸🇴 Somali Shilling (SOS)", value: "SOS", symbol: "Sh" },
  { label: "🇸🇷 Surinamese Dollar (SRD)", value: "SRD", symbol: "$" },
  { label: "🇸🇸 South Sudanese Pound (SSP)", value: "SSP", symbol: "£" },
  {
    label: "🇸🇹 São Tomé and Príncipe Dobra (STD)",
    value: "STD",
    symbol: "Db",
  },
  { label: "🇸🇾 Syrian Pound (SYP)", value: "SYP", symbol: "£" },
  { label: "🇸🇿 Swazi Lilangeni (SZL)", value: "SZL", symbol: "L" },
  { label: "🇹🇭 Thai Baht (THB)", value: "THB", symbol: "฿" },
  { label: "🇹🇿 Tanzanian Shilling (TZS)", value: "TZS", symbol: "Sh" },
  { label: "🇹🇳 Tunisian Dinar (TND)", value: "TND", symbol: "د.ت" },
  { label: "🇹🇷 Turkish Lira (TRY)", value: "TRY", symbol: "₺" },
  {
    label: "🇹🇹 Trinidad and Tobago Dollar (TTD)",
    value: "TTD",
    symbol: "TT$",
  },
  { label: "🇹🇻 Tuvaluan Dollar (TVD)", value: "TVD", symbol: "$" },
  { label: "🇺🇦 Ukrainian Hryvnia (UAH)", value: "UAH", symbol: "₴" },
  { label: "🇺🇬 Ugandan Shilling (UGX)", value: "UGX", symbol: "USh" },
  { label: "🇺🇸 United States Dollar (USD)", value: "USD", symbol: "$" },
  { label: "🇺🇾 Uruguayan Peso (UYU)", value: "UYU", symbol: "$" },
  { label: "🇺🇿 Uzbekistani Som (UZS)", value: "UZS", symbol: "лв" },
  {
    label: "🇻🇪 Venezuelan Bolívar Fuerte (VEF)",
    value: "VEF",
    symbol: "Bs F",
  },
  { label: "🇻🇳 Vietnamese Dong (VND)", value: "VND", symbol: "₫" },
  { label: "🇻🇺 Vanuatu Vatu (VUV)", value: "VUV", symbol: "VT" },
  { label: "🇼🇸 Samoan Tala (WST)", value: "WST", symbol: "T" },
  { label: "🇾🇪 Yemeni Rial (YER)", value: "YER", symbol: "﷼" },
  { label: "🇿🇦 South African Rand (ZAR)", value: "ZAR", symbol: "R" },
  { label: "🇿🇲 Zambian Kwacha (ZMW)", value: "ZMW", symbol: "ZK" },
  { label: "🇿🇼 Zimbabwean Dollar (ZWL)", value: "ZWL", symbol: "$" },
];

export default Currencies;
