const Translations = {
  en: {
    expenseCalculator: "Group Expense Calculator",
    whoPaidHowMuch: "Who paid what?",
    eachMemberPaid: "Who paid and how much?",
    name: "Name",
    amount: "Amount",
    next: "Next",
    invalidAmount: "Invalid amount",
    addMember: "Add member",
    howManyMembers: "How many group members?",
    howManyPeople: "How many people split the bill?",
    numberOfPeople: "Number of people",
    membersBetween1And100:
      "Number of group members must be between %{startNumber} and 100",
    previous: "Back",
    calculate: "Calculate",
    membersPaid: "Members who paid",
    totalPaid: "Total paid:",
    pricePerPerson: "Price per person:",
    member1OwesMember2:
      "%{friend1} owes money to %{friend2}: %{currency}%{amount}",
    share: "Share",
    close: "Close",
    friend: "Person",
  },
  es: {
    expenseCalculator: "Calculadora de gastos grupales",
    whoPaidHowMuch: "¿Quién pagó cuánto?",
    eachMemberPaid: "¿Quién pagó y cuánto?",
    name: "Nombre",
    amount: "Cantidad",
    next: "Siguiente",
    invalidAmount: "Cantidad no válida",
    addMember: "Agregar miembro",
    howManyMembers: "¿Cuántos miembros del grupo?",
    howManyPeople: "¿Cuántas personas dividen la cuenta?",
    numberOfPeople: "Número de personas",
    membersBetween1And100:
      "El número de miembros debe estar entre %{startNumber} y 100",
    previous: "Anterior",
    calculate: "Calcular",
    membersPaid: "Miembros que pagaron",
    totalPaid: "Total pagado:",
    pricePerPerson: "Precio por persona:",
    member1OwesMember2:
      "%{friend1} debe dinero a %{friend2}: %{currency}%{amount}",
    share: "Compartir",
    close: "Cerrar",
    friend: "Persona",
  },
  fr: {
    expenseCalculator: "Calculateur de dépenses de groupe",
    whoPaidHowMuch: "Qui a payé combien?",
    eachMemberPaid: "Qui a payé et combien?",
    name: "Nom",
    amount: "Montant",
    next: "Suivant",
    invalidAmount: "Montant invalide",
    addMember: "Ajouter un membre",
    howManyMembers: "Combien de membres dans le groupe?",
    howManyPeople: "Combien de personnes partagent la facture?",
    numberOfPeople: "Nombre de personnes",
    membersBetween1And100:
      "Le nombre de membres doit être compris entre %{startNumber} et 100",
    previous: "Précédent",
    calculate: "Calculer",
    membersPaid: "Membres qui ont payé",
    totalPaid: "Total payé:",
    pricePerPerson: "Prix par personne:",
    member1OwesMember2:
      "%{friend1} doit de l'argent à %{friend2}: %{currency}%{amount}",
    share: "Partager",
    close: "Fermer",
    friend: "Personne",
  },
  it: {
    expenseCalculator: "Calcolatore di spese di gruppo",
    whoPaidHowMuch: "Chi ha pagato quanto?",
    eachMemberPaid: "Chi ha pagato e quanto?",
    name: "Nome",
    amount: "Importo",
    next: "Avanti",
    invalidAmount: "Importo non valido",
    addMember: "Aggiungi membro",
    howManyMembers: "Quanti membri del gruppo?",
    howManyPeople: "Quante persone dividono il conto?",
    numberOfPeople: "Numero di persone",
    membersBetween1And100:
      "Il numero di membri deve essere compreso tra %{startNumber} e 100",
    previous: "Precedente",
    calculate: "Calcola",
    membersPaid: "Membri che hanno pagato",
    totalPaid: "Totale pagato:",
    pricePerPerson: "Prezzo per persona:",
    member1OwesMember2:
      "%{friend1} deve soldi a %{friend2}: %{currency}%{amount}",
    share: "Condividi",
    close: "Chiudi",
    friend: "Persona",
  },
  de: {
    expenseCalculator: "Gruppen-Ausgabenrechner",
    whoPaidHowMuch: "Wer hat wie viel bezahlt?",
    eachMemberPaid: "Wie viel hat jeder bezahlt?",
    name: "Name",
    amount: "Betrag",
    next: "Weiter",
    invalidAmount: "Ungültiger Betrag",
    addMember: "Mitglied hinzufügen",
    howManyMembers: "Gruppengröße",
    howManyPeople: "Wie viele Personen teilen sich die Rechnung?",
    numberOfPeople: "Anzahl der Personen",
    membersBetween1And100:
      "Die Anzahl der Personen muss zwischen %{startNumber} und 100 liegen",
    previous: "Zurück",
    calculate: "Berechnen",
    membersPaid: "Wer hat was bezahlt?",
    totalPaid: "Insgesamt ausgegeben:",
    pricePerPerson: "Preis pro Person:",
    member1OwesMember2: "%{friend1} schuldet %{friend2}: %{currency}%{amount}",
    share: "Teilen",
    close: "Schließen",
    friend: "Person",
  },
  he: {
    expenseCalculator: "מחשבון ההוצאות של החבר'ה",
    whoPaidHowMuch: "מי שילם וכמה?",
    eachMemberPaid: "כמה כל אחד מהחברים שילם",
    name: "שם",
    amount: "סכום חבר",
    next: "הבא",
    invalidAmount: "סכום כסף לא תקין",
    addMember: "הוסף חבר",
    howManyMembers: "כמה חברה מתחלקים?",
    howManyPeople: "בין כמה אנשים הכסף מתחלק?",
    numberOfPeople: "מספר אנשים",
    membersBetween1And100: "מספר החברים חייב להיות בין %{startNumber} ל100",
    previous: "הקודם",
    calculate: "חשב",
    membersPaid: "החברים ששילמו",
    totalPaid: 'סה"כ שולם:',
    pricePerPerson: "מחיר לאדם:",
    member1OwesMember2:
      "%{friend1} צריך להחזיר כסף ל%{friend2}: %{amount} %{currency}",
    share: "שתף",
    close: "סגור",
    friend: "חבר",
  },
  zh: {
    expenseCalculator: "团体费用计算器",
    whoPaidHowMuch: "谁付了多少钱？",
    eachMemberPaid: "每个成员支付了多少？",
    name: "名字",
    amount: "金额",
    next: "下一步",
    invalidAmount: "无效金额",
    addMember: "添加成员",
    howManyMembers: "有多少成员？",
    howManyPeople: "有多少人分摊账单？",
    numberOfPeople: "人数",
    membersBetween1And100: "成员数必须在 %{startNumber} 到 100 之间",
    previous: "上一步",
    calculate: "计算",
    membersPaid: "支付的成员",
    totalPaid: "总支付:",
    pricePerPerson: "每人价格:",
    member1OwesMember2: "%{friend1} 欠 %{friend2} %{currency}%{amount}",
    share: "分享",
    close: "关闭",
    friend: "成员",
  },
  ja: {
    expenseCalculator: "グループ費用計算機",
    whoPaidHowMuch: "誰がいくら払った？",
    eachMemberPaid: "各メンバーの支払額",
    name: "名前",
    amount: "金額",
    next: "次へ",
    invalidAmount: "無効な金額",
    addMember: "メンバーを追加",
    howManyMembers: "メンバー数は？",
    howManyPeople: "何人で割り勘？",
    numberOfPeople: "人数",
    membersBetween1And100:
      "メンバー数は %{startNumber} ～ 100 の間である必要があります",
    previous: "前へ",
    calculate: "計算",
    membersPaid: "支払ったメンバー",
    totalPaid: "総支払額:",
    pricePerPerson: "一人当たりの価格:",
    member1OwesMember2:
      "%{friend1} は %{friend2} に %{currency}%{amount} を借りています",
    share: "共有",
    close: "閉じる",
    friend: "メンバー",
  },
  ko: {
    expenseCalculator: "그룹 비용 계산기",
    whoPaidHowMuch: "누가 얼마를 지불했나요?",
    eachMemberPaid: "각 멤버가 지불한 금액",
    name: "이름",
    amount: "금액",
    next: "다음",
    invalidAmount: "잘못된 금액",
    addMember: "멤버 추가",
    howManyMembers: "멤버 수는?",
    howManyPeople: "몇 명이서 계산을 나누나요?",
    numberOfPeople: "사람 수",
    membersBetween1And100: "멤버 수는 %{startNumber} 에서 100 사이여야 합니다",
    previous: "이전",
    calculate: "계산",
    membersPaid: "지불한 멤버",
    totalPaid: "총 지불:",
    pricePerPerson: "인당 가격:",
    member1OwesMember2:
      "%{friend1} 은 %{friend2} 에게 %{currency}%{amount} 을 빚졌습니다",
    share: "공유",
    close: "닫기",
    friend: "멤버",
  },
  pt: {
    expenseCalculator: "Calculadora de Despesas do Grupo",
    whoPaidHowMuch: "Quem pagou quanto?",
    eachMemberPaid: "Quanto cada membro pagou",
    name: "Nome",
    amount: "Quantia",
    next: "Próximo",
    invalidAmount: "Quantia inválida",
    addMember: "Adicionar membro",
    howManyMembers: "Quantos membros do grupo?",
    howManyPeople: "Quantas pessoas dividem a conta?",
    numberOfPeople: "Número de pessoas",
    membersBetween1And100:
      "O número de membros deve estar entre %{startNumber} e 100",
    previous: "Anterior",
    calculate: "Calcular",
    membersPaid: "Membros que pagaram",
    totalPaid: "Total pago:",
    pricePerPerson: "Preço por pessoa:",
    member1OwesMember2:
      "%{friend1} deve dinheiro a %{friend2}: %{currency}%{amount}",
    share: "Compartilhar",
    close: "Fechar",
    friend: "Membro",
  },
  ru: {
    expenseCalculator: "Калькулятор расходов группы",
    whoPaidHowMuch: "Кто сколько заплатил?",
    eachMemberPaid: "Сколько заплатил каждый участник",
    name: "Имя",
    amount: "Сумма",
    next: "Далее",
    invalidAmount: "Недопустимая сумма",
    addMember: "Добавить участника",
    howManyMembers: "Сколько участников в группе?",
    howManyPeople: "Сколько человек делят счёт?",
    numberOfPeople: "Количество человек",
    membersBetween1And100:
      "Количество участников должно быть между %{startNumber} и 100",
    previous: "Назад",
    calculate: "Рассчитать",
    membersPaid: "Заплатили участники",
    totalPaid: "Всего заплачено:",
    pricePerPerson: "Цена на человека:",
    member1OwesMember2: "%{friend1} должен %{friend2}: %{currency}%{amount}",
    share: "Поделиться",
    close: "Закрыть",
    friend: "Участник",
  },
  hi: {
    expenseCalculator: "समूह व्यय कैलकुलेटर",
    whoPaidHowMuch: "किसने कितना भुगतान किया?",
    eachMemberPaid: "प्रत्येक सदस्य ने कितना भुगतान किया?",
    name: "नाम",
    amount: "राशि",
    next: "अगला",
    invalidAmount: "अमान्य राशि",
    addMember: "सदस्य जोड़ें",
    howManyMembers: "कितने सदस्य हैं?",
    howManyPeople: "कितने लोग बिल विभाजित कर रहे हैं?",
    numberOfPeople: "लोगों की संख्या",
    membersBetween1And100:
      "सदस्यों की संख्या %{startNumber} और 100 के बीच होनी चाहिए",
    previous: "पिछला",
    calculate: "गणना करें",
    membersPaid: "भुगतान करने वाले सदस्य",
    totalPaid: "कुल भुगतान:",
    pricePerPerson: "प्रति व्यक्ति कीमत:",
    member1OwesMember2:
      "%{friend1} को %{friend2} को %{currency}%{amount} देना है",
    share: "साझा करें",
    close: "बंद करें",
    friend: "सदस्य",
  },
  tr: {
    expenseCalculator: "Grup Gider Hesaplayıcı",
    whoPaidHowMuch: "Kim ne kadar ödedi?",
    eachMemberPaid: "Her üye ne kadar ödedi?",
    name: "İsim",
    amount: "Tutar",
    next: "Sonraki",
    invalidAmount: "Geçersiz tutar",
    addMember: "Üye ekle",
    howManyMembers: "Kaç grup üyesi?",
    howManyPeople: "Kaç kişi faturayı bölüşüyor?",
    numberOfPeople: "Kişi sayısı",
    membersBetween1And100:
      "Grup üyelerinin sayısı %{startNumber} ile 100 arasında olmalıdır",
    previous: "Önceki",
    calculate: "Hesapla",
    membersPaid: "Ödeyen üyeler",
    totalPaid: "Toplam ödenen:",
    pricePerPerson: "Kişi başı fiyat:",
    member1OwesMember2: "%{friend1}, %{friend2}'ye %{currency}%{amount} borçlu",
    share: "Paylaş",
    close: "Kapat",
    friend: "Üye",
  },
};

export default Translations;
