import WizardTranslations from "./wizardTranslations";

const Translations = {
  en: {
    expenseCalculator: "Group Expense Calculator",
    whoPaidHowMuch: "Who paid what?",
    eachMemberPaid: "Who paid and how much?",
    name: "Name",
    amount: "Amount",
    next: "Next",
    invalidAmount: "Invalid amount",
    addMember: "Add member",
    howManyMembers: "How many group members?",
    howManyPeople: "How many people split the bill?",
    numberOfPeople: "Number of people",
    membersBetween1And100:
      "Number of group members must be between %{startNumber} and 100",
    previous: "Back",
    calculate: "Calculate",
    membersPaid: "Members who paid",
    totalPaid: "Total paid:",
    pricePerPerson: "Price per person:",
    member1OwesMember2:
      "%{friend1} owes money to %{friend2}: %{currency}%{amount}",
    share: "Share",
    close: "Close",
    friend: "Person",
    appTitle: 'JUBA',
    appSubtitle: 'Friends Expense Calculator',
    
    // App Description
    whatIsJuba: 'What is JUBA?',
    appDescription: 'JUBA is a smart expense calculator that helps you manage shared expenses between friends in a simple and accurate way',
    addFriendsTitle: 'Add Friends',
    addFriendsDesc: 'Add all friends who participated in purchases or shared expenses',
    recordExpensesTitle: 'Record Expenses',
    recordExpensesDesc: 'Record each friend\'s expenses - restaurants, shopping, travel and more',
    autoCalculationTitle: 'Automatic Calculation',
    autoCalculationDesc: 'The system automatically calculates who needs to pay back whom and how much',
    easySharingTitle: 'Easy Sharing',
    easySharingDesc: 'Share results with friends easily and save lists for future use',
    howItWorksTitle: 'How does it work?',
    step1: 'Add friends who participated in expenses',
    step2: 'Record each person\'s expenses',
    // step3: 'Select who participates in the split (if not everyone)',
    step3: 'Get accurate results - who needs to pay back whom',
    step4: 'Share results or save for later',
  },
  es: {
    expenseCalculator: "Calculadora de gastos grupales",
    whoPaidHowMuch: "¿Quién pagó cuánto?",
    eachMemberPaid: "¿Quién pagó y cuánto?",
    name: "Nombre",
    amount: "Cantidad",
    next: "Siguiente",
    invalidAmount: "Cantidad no válida",
    addMember: "Agregar miembro",
    howManyMembers: "¿Cuántos miembros del grupo?",
    howManyPeople: "¿Cuántas personas dividen la cuenta?",
    numberOfPeople: "Número de personas",
    membersBetween1And100:
      "El número de miembros debe estar entre %{startNumber} y 100",
    previous: "Anterior",
    calculate: "Calcular",
    membersPaid: "Miembros que pagaron",
    totalPaid: "Total pagado:",
    pricePerPerson: "Precio por persona:",
    member1OwesMember2:
      "%{friend1} debe dinero a %{friend2}: %{currency}%{amount}",
    share: "Compartir",
    close: "Cerrar",
    friend: "Persona",

    whatIsJuba: '¿Qué es JUBA?',
    appDescription: 'JUBA es una calculadora inteligente de gastos que te ayuda a gestionar gastos compartidos entre amigos de manera simple y precisa',
    addFriendsTitle: 'Agregar Amigos',
    addFriendsDesc: 'Agrega todos los amigos que participaron en compras o gastos compartidos',
    recordExpensesTitle: 'Registrar Gastos',
    recordExpensesDesc: 'Registra los gastos de cada amigo - restaurantes, compras, viajes y más',
    autoCalculationTitle: 'Cálculo Automático',
    autoCalculationDesc: 'El sistema calcula automáticamente quién necesita pagar a quién y cuánto',
    easySharingTitle: 'Compartir Fácil',
    easySharingDesc: 'Comparte resultados con amigos fácilmente y guarda listas para uso futuro',
    howItWorksTitle: '¿Cómo funciona?',
    step1: 'Agrega amigos que participaron en los gastos',
    step2: 'Registra los gastos de cada persona',
    step3: 'Obtén resultados precisos - quién necesita pagar a quién',
    step4: 'Comparte resultados o guarda para más tarde'
  },
  fr: {
    expenseCalculator: "Calculateur de dépenses de groupe",
    whoPaidHowMuch: "Qui a payé combien?",
    eachMemberPaid: "Qui a payé et combien?",
    name: "Nom",
    amount: "Montant",
    next: "Suivant",
    invalidAmount: "Montant invalide",
    addMember: "Ajouter un membre",
    howManyMembers: "Combien de membres dans le groupe?",
    howManyPeople: "Combien de personnes partagent la facture?",
    numberOfPeople: "Nombre de personnes",
    membersBetween1And100:
      "Le nombre de membres doit être compris entre %{startNumber} et 100",
    previous: "Précédent",
    calculate: "Calculer",
    membersPaid: "Membres qui ont payé",
    totalPaid: "Total payé:",
    pricePerPerson: "Prix par personne:",
    member1OwesMember2:
      "%{friend1} doit de l'argent à %{friend2}: %{currency}%{amount}",
    share: "Partager",
    close: "Fermer",
    friend: "Personne",

    appTitle: 'JUBA',
    appSubtitle: 'Calculateur de Dépenses entre Amis',
    
    // App Description
    whatIsJuba: 'Qu\'est-ce que JUBA?',
    appDescription: 'JUBA est un calculateur de dépenses intelligent qui vous aide à gérer les dépenses partagées entre amis de manière simple et précise',
    addFriendsTitle: 'Ajouter des Amis',
    addFriendsDesc: 'Ajoutez tous les amis qui ont participé aux achats ou aux dépenses partagées',
    recordExpensesTitle: 'Enregistrer les Dépenses',
    recordExpensesDesc: 'Enregistrez les dépenses de chaque ami - restaurants, achats, voyages et plus',
    autoCalculationTitle: 'Calcul Automatique',
    autoCalculationDesc: 'Le système calcule automatiquement qui doit rembourser qui et combien',
    easySharingTitle: 'Partage Facile',
    easySharingDesc: 'Partagez les résultats avec vos amis facilement et sauvegardez les listes pour plus tard',
    howItWorksTitle: 'Comment ça marche?',
    step1: 'Ajoutez les amis qui ont participé aux dépenses',
    step2: 'Enregistrez les dépenses de chaque personne',
    // step3: 'Sélectionnez qui participe au partage (si ce n\'est pas tout le monde)',
    step3: 'Obtenez des résultats précis - qui doit rembourser qui',
    step4: 'Partagez les résultats ou sauvegardez pour plus tard',
  },
  it: {
    expenseCalculator: "Calcolatore di spese di gruppo",
    whoPaidHowMuch: "Chi ha pagato quanto?",
    eachMemberPaid: "Chi ha pagato e quanto?",
    name: "Nome",
    amount: "Importo",
    next: "Avanti",
    invalidAmount: "Importo non valido",
    addMember: "Aggiungi membro",
    howManyMembers: "Quanti membri del gruppo?",
    howManyPeople: "Quante persone dividono il conto?",
    numberOfPeople: "Numero di persone",
    membersBetween1And100:
      "Il numero di membri deve essere compreso tra %{startNumber} e 100",
    previous: "Precedente",
    calculate: "Calcola",
    membersPaid: "Membri che hanno pagato",
    totalPaid: "Totale pagato:",
    pricePerPerson: "Prezzo per persona:",
    member1OwesMember2:
      "%{friend1} deve soldi a %{friend2}: %{currency}%{amount}",
    share: "Condividi",
    close: "Chiudi",
    friend: "Persona",

    whatIsJuba: 'Cos\'è JUBA?',
    appDescription: 'JUBA è una calcolatrice intelligente di spese che ti aiuta a gestire le spese condivise tra amici in modo semplice e preciso',
    addFriendsTitle: 'Aggiungi Amici',
    addFriendsDesc: 'Aggiungi tutti gli amici che hanno partecipato agli acquisti o alle spese condivise',
    recordExpensesTitle: 'Registra Spese',
    recordExpensesDesc: 'Registra le spese di ogni amico - ristoranti, shopping, viaggi e altro',
    autoCalculationTitle: 'Calcolo Automatico',
    autoCalculationDesc: 'Il sistema calcola automaticamente chi deve restituire a chi e quanto',
    easySharingTitle: 'Condivisione Facile',
    easySharingDesc: 'Condividi i risultati con gli amici facilmente e salva le liste per uso futuro',
    howItWorksTitle: 'Come funziona?',
    step1: 'Aggiungi gli amici che hanno partecipato alle spese',
    step2: 'Registra le spese di ogni persona',
    step3: 'Ottieni risultati precisi - chi deve restituire a chi',
    step4: 'Condividi i risultati o salva per dopo'
  },
  de: {
    expenseCalculator: "Gruppen-Ausgabenrechner",
    whoPaidHowMuch: "Wer hat wie viel bezahlt?",
    eachMemberPaid: "Wie viel hat jeder bezahlt?",
    name: "Name",
    amount: "Betrag",
    next: "Weiter",
    invalidAmount: "Ungültiger Betrag",
    addMember: "Mitglied hinzufügen",
    howManyMembers: "Gruppengröße",
    howManyPeople: "Wie viele Personen teilen sich die Rechnung?",
    numberOfPeople: "Anzahl der Personen",
    membersBetween1And100:
      "Die Anzahl der Personen muss zwischen %{startNumber} und 100 liegen",
    previous: "Zurück",
    calculate: "Berechnen",
    membersPaid: "Wer hat was bezahlt?",
    totalPaid: "Insgesamt ausgegeben:",
    pricePerPerson: "Preis pro Person:",
    member1OwesMember2: "%{friend1} schuldet %{friend2}: %{currency}%{amount}",
    share: "Teilen",
    close: "Schließen",
    friend: "Person",

    appTitle: 'JUBA',
    appSubtitle: 'Freunde-Ausgaben-Rechner',
    
    // App Description
    whatIsJuba: 'Was ist JUBA?',
    appDescription: 'JUBA ist ein intelligenter Ausgabenrechner, der Ihnen hilft, gemeinsame Ausgaben zwischen Freunden einfach und genau zu verwalten',
    addFriendsTitle: 'Freunde Hinzufügen',
    addFriendsDesc: 'Fügen Sie alle Freunde hinzu, die an Einkäufen oder gemeinsamen Ausgaben teilgenommen haben',
    recordExpensesTitle: 'Ausgaben Erfassen',
    recordExpensesDesc: 'Erfassen Sie die Ausgaben jedes Freundes - Restaurants, Einkäufe, Reisen und mehr',
    autoCalculationTitle: 'Automatische Berechnung',
    autoCalculationDesc: 'Das System berechnet automatisch, wer wem wie viel zurückzahlen muss',
    easySharingTitle: 'Einfaches Teilen',
    easySharingDesc: 'Teilen Sie Ergebnisse einfach mit Freunden und speichern Sie Listen für später',
    howItWorksTitle: 'Wie funktioniert es?',
    step1: 'Fügen Sie Freunde hinzu, die an den Ausgaben teilgenommen haben',
    step2: 'Erfassen Sie die Ausgaben jeder Person',
    // step3: 'Wählen Sie aus, wer an der Aufteilung teilnimmt (falls nicht alle)',
    step3: 'Erhalten Sie genaue Ergebnisse - wer muss wem zurückzahlen',
    step4: 'Teilen Sie Ergebnisse oder speichern Sie für später',
  },
  he: {
    expenseCalculator: "מחשבון ההוצאות של החבר'ה",
    whoPaidHowMuch: "מי שילם וכמה?",
    eachMemberPaid: "כמה כל אחד מהחברים שילם",
    name: "שם",
    amount: "סכום חבר",
    next: "הבא",
    invalidAmount: "סכום כסף לא תקין",
    addMember: "הוסף חבר",
    howManyMembers: "כמה חברה מתחלקים?",
    howManyPeople: "בין כמה אנשים הכסף מתחלק?",
    numberOfPeople: "מספר אנשים",
    membersBetween1And100: "מספר החברים חייב להיות בין %{startNumber} ל100",
    previous: "הקודם",
    calculate: "חשב",
    membersPaid: "החברים ששילמו",
    totalPaid: 'סה"כ שולם:',
    pricePerPerson: "מחיר לאדם:",
    member1OwesMember2:
      "%{friend1} צריך להחזיר כסף ל%{friend2}: %{amount} %{currency}",
    share: "שתף",
    close: "סגור",
    friend: "חבר",
     appTitle: 'JUBA',
    appSubtitle: 'מחשבון הוצאות חברים',
    
    // App Description
    whatIsJuba: 'מה זה JUBA?',
    appDescription: 'JUBA הוא מחשבון הוצאות חכם שעוזר לכם לנהל הוצאות משותפות בין חברים בצורה פשוטה ומדויקת',
    addFriendsTitle: 'הוספת חברים',
    addFriendsDesc: 'הוסף את כל החברים שהשתתפו ברכישות או בהוצאות המשותפות',
    recordExpensesTitle: 'רישום הוצאות',
    recordExpensesDesc: 'רשום את ההוצאות של כל חבר - מסעדות, קניות, נסיעות ועוד',
    autoCalculationTitle: 'חישוב אוטומטי',
    autoCalculationDesc: 'המערכת מחשבת אוטומטי מי צריך להחזיר למי וכמה',
    easySharingTitle: 'שיתוף קל',
    easySharingDesc: 'שתף את התוצאות עם החברים בקלות ושמור רשימות לעתיד',
    howItWorksTitle: 'איך זה עובד?',
    step1: 'הוסף את החברים שהשתתפו בהוצאות',
    step2: 'רשום את ההוצאות של כל אחד',
    step3: 'קבל תוצאות מדויקות - מי צריך להחזיר למי',
    step4: 'שתף את התוצאות או שמור לעתיד',
  },
  zh: {
    expenseCalculator: "团体费用计算器",
    whoPaidHowMuch: "谁付了多少钱？",
    eachMemberPaid: "每个成员支付了多少？",
    name: "名字",
    amount: "金额",
    next: "下一步",
    invalidAmount: "无效金额",
    addMember: "添加成员",
    howManyMembers: "有多少成员？",
    howManyPeople: "有多少人分摊账单？",
    numberOfPeople: "人数",
    membersBetween1And100: "成员数必须在 %{startNumber} 到 100 之间",
    previous: "上一步",
    calculate: "计算",
    membersPaid: "支付的成员",
    totalPaid: "总支付:",
    pricePerPerson: "每人价格:",
    member1OwesMember2: "%{friend1} 欠 %{friend2} %{currency}%{amount}",
    share: "分享",
    close: "关闭",
    friend: "成员",

    whatIsJuba: '什么是JUBA？',
    appDescription: 'JUBA是一个智能费用计算器，帮助您以简单准确的方式管理朋友间的共同支出',
    addFriendsTitle: '添加朋友',
    addFriendsDesc: '添加所有参与购买或共同支出的朋友',
    recordExpensesTitle: '记录支出',
    recordExpensesDesc: '记录每个朋友的支出 - 餐厅、购物、旅行等',
    autoCalculationTitle: '自动计算',
    autoCalculationDesc: '系统自动计算谁需要还钱给谁以及还多少',
    easySharingTitle: '轻松分享',
    easySharingDesc: '轻松与朋友分享结果，并保存列表以备将来使用',
    howItWorksTitle: '如何使用？',
    step1: '添加参与支出的朋友',
    step2: '记录每个人的支出',
    step3: '获得准确结果 - 谁需要还钱给谁',
    step4: '分享结果或保存以备后用'
  },
  ja: {
    expenseCalculator: "グループ費用計算機",
    whoPaidHowMuch: "誰がいくら払った？",
    eachMemberPaid: "各メンバーの支払額",
    name: "名前",
    amount: "金額",
    next: "次へ",
    invalidAmount: "無効な金額",
    addMember: "メンバーを追加",
    howManyMembers: "メンバー数は？",
    howManyPeople: "何人で割り勘？",
    numberOfPeople: "人数",
    membersBetween1And100:
      "メンバー数は %{startNumber} ～ 100 の間である必要があります",
    previous: "前へ",
    calculate: "計算",
    membersPaid: "支払ったメンバー",
    totalPaid: "総支払額:",
    pricePerPerson: "一人当たりの価格:",
    member1OwesMember2:
      "%{friend1} は %{friend2} に %{currency}%{amount} を借りています",
    share: "共有",
    close: "閉じる",
    friend: "メンバー",

    whatIsJuba: 'JUBAとは何ですか？',
    appDescription: 'JUBAは友達間の共有費用をシンプルかつ正確に管理するのに役立つスマートな費用計算機です',
    addFriendsTitle: '友達を追加',
    addFriendsDesc: '購入や共有費用に参加したすべての友達を追加してください',
    recordExpensesTitle: '支出を記録',
    recordExpensesDesc: '各友達の支出を記録 - レストラン、ショッピング、旅行など',
    autoCalculationTitle: '自動計算',
    autoCalculationDesc: 'システムが誰が誰にいくら返済する必要があるかを自動的に計算します',
    easySharingTitle: '簡単な共有',
    easySharingDesc: '友達と結果を簡単に共有し、リストを保存して今後の使用に備えます',
    howItWorksTitle: 'どのように動作しますか？',
    step1: '支出に参加した友達を追加',
    step2: '各人の支出を記録',
    step3: '正確な結果を取得 - 誰が誰に返済する必要があるか',
    step4: '結果を共有するか、後で使用するために保存'
  },
  ko: {
    expenseCalculator: "그룹 비용 계산기",
    whoPaidHowMuch: "누가 얼마를 지불했나요?",
    eachMemberPaid: "각 멤버가 지불한 금액",
    name: "이름",
    amount: "금액",
    next: "다음",
    invalidAmount: "잘못된 금액",
    addMember: "멤버 추가",
    howManyMembers: "멤버 수는?",
    howManyPeople: "몇 명이서 계산을 나누나요?",
    numberOfPeople: "사람 수",
    membersBetween1And100: "멤버 수는 %{startNumber} 에서 100 사이여야 합니다",
    previous: "이전",
    calculate: "계산",
    membersPaid: "지불한 멤버",
    totalPaid: "총 지불:",
    pricePerPerson: "인당 가격:",
    member1OwesMember2:
      "%{friend1} 은 %{friend2} 에게 %{currency}%{amount} 을 빚졌습니다",
    share: "공유",
    close: "닫기",
    friend: "멤버",

    whatIsJuba: 'JUBA란 무엇인가요?',
    appDescription: 'JUBA는 친구들 간의 공유 비용을 간단하고 정확하게 관리하는 데 도움을 주는 스마트 비용 계산기입니다',
    addFriendsTitle: '친구 추가',
    addFriendsDesc: '구매나 공유 비용에 참여한 모든 친구들을 추가하세요',
    recordExpensesTitle: '비용 기록',
    recordExpensesDesc: '각 친구의 비용을 기록하세요 - 레스토랑, 쇼핑, 여행 등',
    autoCalculationTitle: '자동 계산',
    autoCalculationDesc: '시스템이 누가 누구에게 얼마를 갚아야 하는지 자동으로 계산합니다',
    easySharingTitle: '쉬운 공유',
    easySharingDesc: '친구들과 결과를 쉽게 공유하고 향후 사용을 위해 목록을 저장하세요',
    howItWorksTitle: '어떻게 작동하나요?',
    step1: '비용에 참여한 친구들을 추가',
    step2: '각 사람의 비용을 기록',
    step3: '정확한 결과 얻기 - 누가 누구에게 갚아야 하는지',
    step4: '결과를 공유하거나 나중을 위해 저장'
  },
  pt: {
    expenseCalculator: "Calculadora de Despesas do Grupo",
    whoPaidHowMuch: "Quem pagou quanto?",
    eachMemberPaid: "Quanto cada membro pagou",
    name: "Nome",
    amount: "Quantia",
    next: "Próximo",
    invalidAmount: "Quantia inválida",
    addMember: "Adicionar membro",
    howManyMembers: "Quantos membros do grupo?",
    howManyPeople: "Quantas pessoas dividem a conta?",
    numberOfPeople: "Número de pessoas",
    membersBetween1And100:
      "O número de membros deve estar entre %{startNumber} e 100",
    previous: "Anterior",
    calculate: "Calcular",
    membersPaid: "Membros que pagaram",
    totalPaid: "Total pago:",
    pricePerPerson: "Preço por pessoa:",
    member1OwesMember2:
      "%{friend1} deve dinheiro a %{friend2}: %{currency}%{amount}",
    share: "Compartilhar",
    close: "Fechar",
    friend: "Membro",

    whatIsJuba: 'O que é JUBA?',
    appDescription: 'JUBA é uma calculadora inteligente de despesas que ajuda você a gerenciar despesas compartilhadas entre amigos de forma simples e precisa',
    addFriendsTitle: 'Adicionar Amigos',
    addFriendsDesc: 'Adicione todos os amigos que participaram de compras ou despesas compartilhadas',
    recordExpensesTitle: 'Registrar Despesas',
    recordExpensesDesc: 'Registre as despesas de cada amigo - restaurantes, compras, viagens e mais',
    autoCalculationTitle: 'Cálculo Automático',
    autoCalculationDesc: 'O sistema calcula automaticamente quem precisa pagar de volta para quem e quanto',
    easySharingTitle: 'Compartilhamento Fácil',
    easySharingDesc: 'Compartilhe resultados com amigos facilmente e salve listas para uso futuro',
    howItWorksTitle: 'Como funciona?',
    step1: 'Adicione amigos que participaram das despesas',
    step2: 'Registre as despesas de cada pessoa',
    step3: 'Obtenha resultados precisos - quem precisa pagar de volta para quem',
    step4: 'Compartilhe resultados ou salve para mais tarde'
  },
  ru: {
    expenseCalculator: "Калькулятор расходов группы",
    whoPaidHowMuch: "Кто сколько заплатил?",
    eachMemberPaid: "Сколько заплатил каждый участник",
    name: "Имя",
    amount: "Сумма",
    next: "Далее",
    invalidAmount: "Недопустимая сумма",
    addMember: "Добавить участника",
    howManyMembers: "Сколько участников в группе?",
    howManyPeople: "Сколько человек делят счёт?",
    numberOfPeople: "Количество человек",
    membersBetween1And100:
      "Количество участников должно быть между %{startNumber} и 100",
    previous: "Назад",
    calculate: "Рассчитать",
    membersPaid: "Заплатили участники",
    totalPaid: "Всего заплачено:",
    pricePerPerson: "Цена на человека:",
    member1OwesMember2: "%{friend1} должен %{friend2}: %{currency}%{amount}",
    share: "Поделиться",
    close: "Закрыть",
    friend: "Участник",

    whatIsJuba: 'Что такое JUBA?',
    appDescription: 'JUBA - это умный калькулятор расходов, который помогает управлять общими расходами между друзьями простым и точным способом',
    addFriendsTitle: 'Добавить Друзей',
    addFriendsDesc: 'Добавьте всех друзей, которые участвовали в покупках или общих расходах',
    recordExpensesTitle: 'Записать Расходы',
    recordExpensesDesc: 'Записывайте расходы каждого друга - рестораны, покупки, путешествия и многое другое',
    autoCalculationTitle: 'Автоматический Расчет',
    autoCalculationDesc: 'Система автоматически рассчитывает, кто кому должен и сколько',
    easySharingTitle: 'Легкое Деление',
    easySharingDesc: 'Легко делитесь результатами с друзьями и сохраняйте списки для будущего использования',
    howItWorksTitle: 'Как это работает?',
    step1: 'Добавьте друзей, участвовавших в расходах',
    step2: 'Запишите расходы каждого человека',
    step3: 'Получите точные результаты - кто кому должен',
    step4: 'Поделитесь результатами или сохраните на потом'
  },
  hi: {
    expenseCalculator: "समूह व्यय कैलकुलेटर",
    whoPaidHowMuch: "किसने कितना भुगतान किया?",
    eachMemberPaid: "प्रत्येक सदस्य ने कितना भुगतान किया?",
    name: "नाम",
    amount: "राशि",
    next: "अगला",
    invalidAmount: "अमान्य राशि",
    addMember: "सदस्य जोड़ें",
    howManyMembers: "कितने सदस्य हैं?",
    howManyPeople: "कितने लोग बिल विभाजित कर रहे हैं?",
    numberOfPeople: "लोगों की संख्या",
    membersBetween1And100:
      "सदस्यों की संख्या %{startNumber} और 100 के बीच होनी चाहिए",
    previous: "पिछला",
    calculate: "गणना करें",
    membersPaid: "भुगतान करने वाले सदस्य",
    totalPaid: "कुल भुगतान:",
    pricePerPerson: "प्रति व्यक्ति कीमत:",
    member1OwesMember2:
      "%{friend1} को %{friend2} को %{currency}%{amount} देना है",
    share: "साझा करें",
    close: "बंद करें",
    friend: "सदस्य",

      whatIsJuba: 'JUBA क्या है?',
      appDescription: 'JUBA एक स्मार्ट खर्च कैलकुलेटर है जो आपको दोस्तों के बीच साझा खर्चों को सरल और सटीक तरीके से प्रबंधित करने में मदद करता है',
      addFriendsTitle: 'दोस्त जोड़ें',
      addFriendsDesc: 'उन सभी दोस्तों को जोड़ें जिन्होंने खरीदारी या साझा खर्चों में भाग लिया है',
      recordExpensesTitle: 'खर्च रिकॉर्ड करें',
      recordExpensesDesc: 'प्रत्येक दोस्त के खर्च रिकॉर्ड करें - रेस्तराँ, शॉपिंग, यात्रा और अधिक',
      autoCalculationTitle: 'स्वचालित गणना',
      autoCalculationDesc: 'सिस्टम स्वचालित रूप से गणना करता है कि किसे किसको कितना पैसा वापस करना है',
      easySharingTitle: 'आसान साझाकरण',
      easySharingDesc: 'दोस्तों के साथ परिणाम आसानी से साझा करें और भविष्य के उपयोग के लिए सूचियाँ सहेजें',
      howItWorksTitle: 'यह कैसे काम करता है?',
      step1: 'खर्चों में भाग लेने वाले दोस्तों को जोड़ें',
      step2: 'प्रत्येक व्यक्ति के खर्च रिकॉर्ड करें',
      step3: 'सटीक परिणाम प्राप्त करें - किसे किसको पैसा वापस करना है',
      step4: 'परिणाम साझा करें या बाद के लिए सहेजें'
  },
  tr: {
    expenseCalculator: "Grup Gider Hesaplayıcı",
    whoPaidHowMuch: "Kim ne kadar ödedi?",
    eachMemberPaid: "Her üye ne kadar ödedi?",
    name: "İsim",
    amount: "Tutar",
    next: "Sonraki",
    invalidAmount: "Geçersiz tutar",
    addMember: "Üye ekle",
    howManyMembers: "Kaç grup üyesi?",
    howManyPeople: "Kaç kişi faturayı bölüşüyor?",
    numberOfPeople: "Kişi sayısı",
    membersBetween1And100:
      "Grup üyelerinin sayısı %{startNumber} ile 100 arasında olmalıdır",
    previous: "Önceki",
    calculate: "Hesapla",
    membersPaid: "Ödeyen üyeler",
    totalPaid: "Toplam ödenen:",
    pricePerPerson: "Kişi başı fiyat:",
    member1OwesMember2: "%{friend1}, %{friend2}'ye %{currency}%{amount} borçlu",
    share: "Paylaş",
    close: "Kapat",
    friend: "Üye",

    whatIsJuba: 'JUBA nedir?',
    appDescription: 'JUBA, arkadaşlar arasındaki ortak harcamaları basit ve doğru bir şekilde yönetmenize yardımcı olan akıllı bir harcama hesaplayicısıdır',
    addFriendsTitle: 'Arkadaş Ekle',
    addFriendsDesc: 'Alışveriş veya ortak harcamalara katılan tüm arkadaşlarınızı ekleyin',
    recordExpensesTitle: 'Harcamaları Kaydet',
    recordExpensesDesc: 'Her arkadaşınızın harcamalarını kaydedin - restoranlar, alışveriş, seyahat ve daha fazlası',
    autoCalculationTitle: 'Otomatik Hesaplama',
    autoCalculationDesc: 'Sistem kimin kime ne kadar geri ödemesi gerektiğini otomatik olarak hesaplar',
    easySharingTitle: 'Kolay Paylaşım',
    easySharingDesc: 'Sonuçları arkadaşlarla kolayca paylaşın ve gelecekte kullanmak üzere listeleri kaydedin',
    howItWorksTitle: 'Nasıl çalışır?',
    step1: 'Harcamalara katılan arkadaşları ekleyin',
    step2: 'Her kişinin harcamalarını kaydedin',
    step3: 'Doğru sonuçları alın - kimin kime geri ödemesi gerekiyor',
    step4: 'Sonuçları paylaşın veya daha sonra için kaydedin'
  },
};

Object.keys(WizardTranslations).forEach((locale) => {
  Object.assign(Translations[locale], WizardTranslations[locale]);
});

export default Translations;